### ISSUE TITLE
Skip locked videos

### ISSUE THREAD

**Issue by shopgirl284** [plexinc-plugins/FOX.bundle#5]
The Fox channel lists all the videos for each show in the All Shows section.

Since locked videos will not play, we need to add code to skip these locked videos so they will not show up in the listings for each show and only unlocked free videos will be listed.

**Comment by shopgirl284** [comment]
There is not an issue with locked videos.

The issue is that none of the pages for their videos have source code any more.

Example: Episode 13 of Beat Shazam. The URL that is provided from the home page for that video is https://www.fox.com/watch/4370e4cbdc380c49cbc414dda101bab1/. But if you go to that page and try to pull the source code, the source code is for http://www.fox.com/

**Comment by shopgirl284** [comment]
The plugin and URL service for this website will have to be completely rewritten.

**Comment by sander1** [comment]
> The plugin and URL service for this website will have to be completely rewritten.

The URL Service has been rewritten, looking into the channel next.

**Comment by sander1** [comment]
All updated! Skipping locked episodes means that some directories will be empty though...
